import express from 'express';
import upload from '../middlewares/multers.js';
import { addcomment, addnewpost, bookmarkpost, deletepost, dislikepost, getallpost, getcommentofpost, getuserpost, likepost } from '../controllers/post.controller.js';
import isAuthenticated from '../middlewares/isAuthenticated.js';
const router = express.Router();
router.route("/addpost").post(isAuthenticated,upload.single('image'),addnewpost);
router.route("/all").get(isAuthenticated,getallpost);
router.route("/userpost/all").get(isAuthenticated,getuserpost);
router.route("/:id/like").get(isAuthenticated,likepost);
router.route("/:id/dislike").get(isAuthenticated,dislikepost);
router.route("/:id/comment").post(isAuthenticated,addcomment);
router.route("/:id/comment/all").post(isAuthenticated,getcommentofpost);
router.route("/delete/:id").post(isAuthenticated,deletepost);
router.route("/:id/bookmark").post(isAuthenticated,bookmarkpost);
export default router;
